<?php include ("views/headers/headerDocente.html"); ?>

<div class="d-flex justify-content-center">
    <div class="col-md-10 p-4">

        <div class="card">
            
            <div class="card-header bg-primary">
                <h5  class = "text-white text-center">CREAR LECTURA</h5>
            </div>

            <div class="card-body">
               
                <form action= "#" method="POST">
                    
                    <div class="form-group row p-2">
                        <label class="col-form-label col-md-1">Título:</label>
                        <input type="text" class="form-control col-md-7" name="titulo" placeholder="Título de la lectura" required>
                        <div class = "col-sm-1"></div>
                        
                        <select class="form-control col-sm-2 " name = "id_grado" id="id_grado " required>
                        
                        <option selected disabled value="">Grado</option>
                        <?php  foreach ($grados as $grado) { ?> 
                        <option value ="<?=$grado['id_grado']?>"><?=$grado['code']?></option>
                        <?php  } ?>
                        </select>

                    </div>
                    <div class="form-group p-2">
                        <label>Contenido</label>
                        <textarea id= "ckeditor" class="ckeditor" name="contenido" required> </textarea>
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary ">Guardar lectura</button>
                    </div>
                    
                </form>
            </div>
        </div>
                     <?php if(!empty($message)): ?>
                        <div class="col-md-12 p-2">
                        <div class="alert alert-success" role="alert"> <?= $message ?></div> </div> 
                    <?php endif; ?>
    </div>
    </div>
 
</body>
</html>
<?php include ("views/footers/footer.html"); ?>