<?php include ("views/headers/headerDocente.html"); ?>

  <div class="col-md-12 p-4">

  <div class="card">

  <div class="d-flex justify-content-center p-2">
            <label><h4>Lista de lecturas</h4></label>
        </div>

    <table class = "table table-striped">

        <thead>
            <tr>
                <th>ID</th>
                <th>Título</th>
                <th>Contenido</th>
                <th>Fecha de Creación</th>
                <th>Grado</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody id = "datos">

        </tbody>
    </table>

    </div>
</div>

    </body>
</html>

<?php include ("views/footers/footer.html"); ?>

<script type = "text/javascript">

$(document).ready(function(){
    listarLecturas( <?php echo $id_profesor ?> );
}); 
</script>