<?php include ("headers/headerLogin.html"); ?>

<div class="d-flex justify-content-center">
    <div class="col-md-5 p-4">

        <div class="card">
            
            <div class="card-header bg-primary">
                <h5  class = "text-white text-center">VERIFICACIÓN EN DOS PASOS</h5>
            </div>

            <div class="card-body">
               
                <form action= "#" method="POST">
                    <div class="text-center">
                        <p>Hemos enviado un código de verificación de 6 dígitos al correo electrónico asociado a su 
                        usuario, por favor verifique su bandeja de entrada e introduzca el código para iniciar sesión</p>
                    </div>
                    
                    <div class="form-group">
                        <input type="number" class="form-control" name="token" placeholder="Ingrese el código" required>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-primary  btn-block">Verificar código</button>
                    </div>
                    
                </form>
            </div>
        </div>

        <?php if(!empty($message)): ?>
            <script type = "text/javascript">

                    alert("<?php echo $message ?>");
                    window.location.replace("index.php");

                </script>
        <?php endif; ?>

    </div>
    </div>
 
</body>
</html>

<?php include ("footers/footer.html"); ?>

