<?php include ("views/headers/headerEstudiante.html"); ?>

<div class="d-flex justify-content-center">
    <div class="col-md-10 p-4">
        <div class='card'>

        <div class= 'card-header text-center'>
        <?php  echo "<h1> Bienvenido/a $usuario!</h1>"; ?>

        </div>

        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                <img src="https://cdn.mequieroir.com/wp-content/uploads/2020/08/estudiantes_masks_home.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Good mornign student!</h5>
                    <p>How we want to break free!</p>
                </div>
                </div>
                <div class="carousel-item">
                <img src="https://s3.amazonaws.com/rtvc-assets-canalinstitucional.tv/s3fs-public/styles/interna_noticias_1222x647/public/images/estudiar_2020_nota.jpeg?itok=UrH66DFy" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Good afternoon teacher</h5>
                    <p>You can to create a lesson with its questions</p>
                </div>
                </div>
                <div class="carousel-item">
                <img src="https://israelnoticias.com/wp-content/uploads/2020/11/secundaria-Israel-jpg.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <?php

            echo "<h3> Grado: ".$grado."</h3>"          
            
        ?>
    </body>
</html>

<?php include ("views/footers/footer.html"); ?>